FROM python:3.10-rc-buster 

#work directory of applictation
WORKDIR /prawapp


#Install dependencies 
copy requirements.txt .
RUN pip install -r requirements.txt 


#Copy the Source Code
COPY /prawapp . 


#Run the Application 
CMD ["python3","praw-1.py"]